# namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: release-intel
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-intel-app
  namespace: release-intel
  labels:
    app: release-intel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release-intel
  template:
    metadata:
      labels:
        app: release-intel
    spec:
      restartPolicy: Always
      containers:
      - name: release-intel
        image: nixndme/morpheus-release-intel:latest   # replace tag
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-intel-svc
  namespace: release-intel
  labels:
    app: release-intel
spec:
  selector:
    app: release-intel
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-intel
  namespace: release-intel
  labels:
    app: release-intel
spec:
  rules:
  - host: "release-intel.init0xff.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: release-intel-svc
            port:
              number: 3000
